export const data = {
  expense: [
    {
      category: "Grocery",
      date: "2022-07-01",
      location: "Walmart",
      amount: "95.00",
      payment_method: "Discover",
      remarks: "weekly grocery",
    },
    {
      category: "Grocery",
      date: "2022-07-01",
      location: "Walmart",
      amount: "95.00",
      payment_method: "Discover",
      remarks: "weekly grocery",
    },
    {
      category: "Grocery",
      date: "2022-07-01",
      location: "Walmart",
      amount: "95.00",
      payment_method: "Discover",
      remarks: "weekly grocery",
    },
    {
      category: "Grocery",
      date: "2022-07-01",
      location: "Walmart",
      amount: "95.00",
      payment_method: "Discover",
      remarks: "weekly grocery",
    },
    {
      category: "Grocery",
      date: "2022-07-01",
      location: "Walmart",
      amount: "95.00",
      payment_method: "Discover",
      remarks: "weekly grocery",
    },
    {
      category: "Grocery",
      date: "2022-07-01",
      location: "Walmart",
      amount: "95.00",
      payment_method: "Discover",
      remarks: "weekly grocery",
    },
    {
      category: "Grocery",
      date: "2022-07-01",
      location: "Walmart",
      amount: "95.00",
      payment_method: "Discover",
      remarks: "weekly grocery",
    },
  ],
};
